user:
  name: 
  password: 
option:
  driver: msedge
  browser_path: 
  delay_time_s: 10
  enabled_random_time: True
  question_classification: 0

question-urls:
  - 
  - 
  - 
  - 

OpenAI:
  base_url: "https://api.suanli.cn/v1"
  api_key: "sk-W0rpStc95T7JVYVwDYc29IyirjtpPPby6SozFMQr17m8KWeo"
  model: "free:QwQ-32B"
  max_tokens: 1000
  temperature: 0.3
