user:
  name: 
  password: 
option:
  driver: msedge
  browser_path: 
  delay_time_s: 10
  enabled_random_time: True
  question_classification: 0

question-urls:
  - 
  - 
  - 
  - 

OpenAI:
  base_url: "http://localhost:11434/v1"
  api_key: "ollama"
  model: "deepseek-r1:latest"
  max_tokens: 1000
  temperature: 0.3
