user:
  name:
  password:
option:
  driver: msedge
  browser_path:
  delay_time_s: 10
  enabled_random_time: True
  question_classification: 1

question-urls:
  -
  -
  -
  -

OpenAI:
  #这是免费的qwqAPI，有点慢本地的ollama更合适
  base_url: "https://api.suanli.cn/v1"
  api_key: "sk-W0rpStc95T7JVYVwDYc29IyirjtpPPby6SozFMQr17m8KWeo"
  model: "free:QwQ-32B"
  # base_url: "http://localhost:11434/v1"
  # api_key: "ollama"
  # model: "deepseek-r1:1.5b"
  max_tokens: 1000
  temperature: 0.3
